2019-06-24 09:36:58,292 ERROR 5573 [-/127.0.0.1/-/31ms POST /api/sp_org] nodejs.RequestError: connect ECONNREFUSED 0.0.0.0:8088, POST http://0.0.0.0:8088/api/sp_org -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":1,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"0.0.0.0:8088:":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "0.0.0.0"
port: 8088
name: "RequestError"
data: undefined
path: "/api/sp_org"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":8,"keepAliveSocket":false,"requestUrls":["http://0.0.0.0:8088/api/sp_org"],"timing":null,"remoteAddress":"","remotePort":"","socketHandledRequests":1,"socketHandledResponses":0}
pid: 5573
hostname: hust-H110M-S2

2019-06-24 14:56:32,129 ERROR 14740 [-/127.0.0.1/-/16ms GET /api/sp_org_initialized] nodejs.TypeError: Cannot read property 'findOne' of undefined
    at UserService.fetch_sp_org (/home/hust/user/sp-dashboard/src/app/service/user.js:31:48)
    at HomeController.fetch_spOrg (/home/hust/user/sp-dashboard/src/app/controller/home.js:53:48)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at next (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:45:18)
    at /home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at /home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:36:12
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at passportSession (/home/hust/user/sp-dashboard/src/node_modules/egg-passport/lib/framework.js:59:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 14740
hostname: hust-H110M-S2

2019-06-24 14:56:35,504 ERROR 14740 [-/127.0.0.1/-/1ms GET /api/sp_org_initialized] nodejs.TypeError: Cannot read property 'findOne' of undefined
    at UserService.fetch_sp_org (/home/hust/user/sp-dashboard/src/app/service/user.js:31:48)
    at HomeController.fetch_spOrg (/home/hust/user/sp-dashboard/src/app/controller/home.js:53:48)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at next (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:45:18)
    at /home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at /home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:36:12
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at passportSession (/home/hust/user/sp-dashboard/src/node_modules/egg-passport/lib/framework.js:59:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 14740
hostname: hust-H110M-S2

2019-06-24 14:58:38,507 ERROR 14902 [-/127.0.0.1/-/1ms GET /api/sp_org_initialized] nodejs.TypeError: Cannot read property 'findOne' of undefined
    at UserService.fetch_sp_org (/home/hust/user/sp-dashboard/src/app/service/user.js:31:48)
    at HomeController.fetch_spOrg (/home/hust/user/sp-dashboard/src/app/controller/home.js:53:48)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at next (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:45:18)
    at /home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at /home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:36:12
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at passportSession (/home/hust/user/sp-dashboard/src/node_modules/egg-passport/lib/framework.js:59:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 14902
hostname: hust-H110M-S2

2019-06-24 15:30:44,926 ERROR 16105 [-/127.0.0.1/-/17ms GET /api/sp_org_initialized] nodejs.TypeError: Cannot read property 'toJSON' of undefined
    at UserService.fetch_sp_org (/home/hust/user/sp-dashboard/src/app/service/user.js:38:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 16105
hostname: hust-H110M-S2

2019-06-24 15:35:39,915 ERROR 16364 [-/127.0.0.1/-/13ms GET /api/sp_org_initialized] nodejs.TypeError: Cannot read property 'toISOString' of undefined
    at UserService.fetch_sp_org (/home/hust/user/sp-dashboard/src/app/service/user.js:38:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 16364
hostname: hust-H110M-S2

2019-06-24 15:36:44,650 ERROR 16595 [-/127.0.0.1/-/12ms GET /api/sp_org_initialized] nodejs.TypeError: Cannot read property 'toString' of undefined
    at UserService.fetch_sp_org (/home/hust/user/sp-dashboard/src/app/service/user.js:38:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 16595
hostname: hust-H110M-S2

2019-06-24 15:39:18,436 ERROR 16828 [-/127.0.0.1/-/16ms GET /api/sp_org_initialized] nodejs.TypeError: Cannot read property 'toString' of undefined
    at UserService.fetch_sp_org (/home/hust/user/sp-dashboard/src/app/service/user.js:39:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 16828
hostname: hust-H110M-S2

2019-06-24 15:40:05,015 ERROR 16911 [-/127.0.0.1/-/24ms GET /api/sp_org_initialized] nodejs.TypeError: Cannot read property 'toString' of undefined
    at UserService.fetch_sp_org (/home/hust/user/sp-dashboard/src/app/service/user.js:39:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 16911
hostname: hust-H110M-S2

2019-06-24 15:48:52,480 ERROR 17139 [-/127.0.0.1/-/20ms GET /api/sp_org_initialized] nodejs.TypeError: Cannot read property 'toString' of undefined
    at UserService.fetch_sp_org (/home/hust/user/sp-dashboard/src/app/service/user.js:39:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 17139
hostname: hust-H110M-S2

2019-06-24 15:51:23,100 ERROR 17321 [-/127.0.0.1/-/26ms GET /api/sp_org_initialized] nodejs.RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at UserService.fetch_sp_org (/home/hust/user/sp-dashboard/src/app/service/user.js:40:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 17321
hostname: hust-H110M-S2

2019-06-24 16:05:12,691 ERROR 17835 [-/127.0.0.1/-/14ms GET /api/sp_org_initialized] nodejs.RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at UserService.fetch_sp_org (/home/hust/user/sp-dashboard/src/app/service/user.js:34:47)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 17835
hostname: hust-H110M-S2

2019-06-24 16:10:39,354 ERROR 18039 [-/127.0.0.1/-/13ms GET /api/sp_org_initialized] nodejs.RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at UserService.fetch_sp_org (/home/hust/user/sp-dashboard/src/app/service/user.js:34:47)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 18039
hostname: hust-H110M-S2

2019-06-24 16:59:33,592 ERROR 20680 [-/127.0.0.1/-/30ms GET /api/sp_org_initialized] nodejs.TypeError: Cannot read property 'toString' of undefined
    at UserService.fetch_sp_org (/home/hust/user/sp-dashboard/src/app/service/user.js:42:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 20680
hostname: hust-H110M-S2

2019-06-24 17:02:09,389 ERROR 20907 [-/127.0.0.1/-/0ms GET /] nodejs.ReferenceError: ISODate is not defined
    at module.exports.app (/home/hust/user/sp-dashboard/src/app/model/sporg.js:11:23)
    at getExports (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/file_loader.js:220:15)
    at FileLoader.parse (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/file_loader.js:158:25)
    at FileLoader.load (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/file_loader.js:67:24)
    at AppWorkerLoader.loadToApp (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/egg_loader.js:388:25)
    at loadModelToApp (/home/hust/user/sp-dashboard/src/node_modules/egg-mongoose/lib/mongoose.js:97:14)
    at app.beforeStart (/home/hust/user/sp-dashboard/src/node_modules/egg-mongoose/lib/mongoose.js:43:7)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/lifecycle.js:248:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

pid: 20907
hostname: hust-H110M-S2

2019-06-24 17:02:19,491 ERROR 20957 [-/127.0.0.1/-/0ms GET /] nodejs.ReferenceError: ISODate is not defined
    at module.exports.app (/home/hust/user/sp-dashboard/src/app/model/sporg.js:11:23)
    at getExports (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/file_loader.js:220:15)
    at FileLoader.parse (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/file_loader.js:158:25)
    at FileLoader.load (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/file_loader.js:67:24)
    at AppWorkerLoader.loadToApp (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/egg_loader.js:388:25)
    at loadModelToApp (/home/hust/user/sp-dashboard/src/node_modules/egg-mongoose/lib/mongoose.js:97:14)
    at app.beforeStart (/home/hust/user/sp-dashboard/src/node_modules/egg-mongoose/lib/mongoose.js:43:7)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/lifecycle.js:248:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

pid: 20957
hostname: hust-H110M-S2

2019-06-24 17:04:28,157 ERROR 21215 [-/127.0.0.1/-/15ms GET /api/sp_org_initialized] nodejs.RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at UserService.fetch_sp_org (/home/hust/user/sp-dashboard/src/app/service/user.js:34:47)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 21215
hostname: hust-H110M-S2

2019-06-26 15:49:48,338 ERROR 7759 [-/127.0.0.1/-/0ms GET /] nodejs.MongoError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/hust/user/sp-dashboard/src/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/home/hust/user/sp-dashboard/src/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/home/hust/user/sp-dashboard/src/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
name: "MongoError"
message: "[egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"
pid: 7759
hostname: hust-H110M-S2

2019-06-27 15:44:50,256 ERROR 10311 [-/127.0.0.1/-/216ms POST /api/create_channel] nodejs.ReferenceError: ctx is not defined
    at ChannelService.create_channel (/home/hust/user/sp-dashboard/src/app/service/channel.js:7:5)
    at ChannelController.create_channel (/home/hust/user/sp-dashboard/src/app/controller/channel.js:16:31)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at next (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:45:18)
    at /home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at /home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:36:12
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at passportSession (/home/hust/user/sp-dashboard/src/node_modules/egg-passport/lib/framework.js:59:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 10311
hostname: hust-H110M-S2

2019-06-27 15:46:54,777 ERROR 10448 [-/127.0.0.1/-/211ms POST /api/create_channel] nodejs.ReferenceError: network is not defined
    at ChannelService.create_channel (/home/hust/user/sp-dashboard/src/app/service/channel.js:8:29)
    at ChannelController.create_channel (/home/hust/user/sp-dashboard/src/app/controller/channel.js:16:31)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at next (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:45:18)
    at /home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at /home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:36:12
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at passportSession (/home/hust/user/sp-dashboard/src/node_modules/egg-passport/lib/framework.js:59:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 10448
hostname: hust-H110M-S2

2019-06-27 15:51:25,179 ERROR 10578 [-/127.0.0.1/-/6ms POST /api/create_channel] nodejs.TypeError: ctx.createChannel is not a function
    at ChannelService.create_channel (/home/hust/user/sp-dashboard/src/app/service/channel.js:10:15)
    at ChannelController.create_channel (/home/hust/user/sp-dashboard/src/app/controller/channel.js:16:31)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at next (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:45:18)
    at /home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at /home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:36:12
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at passportSession (/home/hust/user/sp-dashboard/src/node_modules/egg-passport/lib/framework.js:59:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 10578
hostname: hust-H110M-S2

2019-06-27 15:55:33,140 ERROR 10732 Error: Invalid network configuration due to missing configuration data
    at _getNetworkConfig (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:1921:9)
    at Function.loadFromConfig (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:114:28)
    at getClientForOrg (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:39:24)
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:103:28)
    at Object.createChannel (/home/hust/user/sp-dashboard/src/app/lib/fabric/index.js:33:26)
    at ChannelService.create_channel (/home/hust/user/sp-dashboard/src/app/service/channel.js:10:15)
    at ChannelController.create_channel (/home/hust/user/sp-dashboard/src/app/controller/channel.js:16:31)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at next (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:45:18)
    at /home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at /home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:36:12
2019-06-27 15:55:33,141 ERROR 10732 [-/127.0.0.1/-/21ms POST /api/create_channel] nodejs.Error: Failed to initialize the channel: Error: Invalid network configuration due to missing configuration data
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:133:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 10732
hostname: hust-H110M-S2

2019-06-27 16:04:25,104 ERROR 11033 Error: Invalid network configuration due to missing configuration data
    at _getNetworkConfig (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:1921:9)
    at Function.loadFromConfig (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:114:28)
    at getClientForOrg (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:39:24)
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:103:28)
    at Object.createChannel (/home/hust/user/sp-dashboard/src/app/lib/fabric/index.js:33:26)
    at ChannelService.create_channel (/home/hust/user/sp-dashboard/src/app/service/channel.js:10:15)
    at ChannelController.create_channel (/home/hust/user/sp-dashboard/src/app/controller/channel.js:16:31)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at next (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:45:18)
    at /home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at /home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:36:12
2019-06-27 16:04:25,108 ERROR 11033 [-/127.0.0.1/-/51ms POST /api/create_channel] nodejs.Error: Failed to initialize the channel: Error: Invalid network configuration due to missing configuration data
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:133:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 11033
hostname: hust-H110M-S2

2019-06-27 16:22:13,403 ERROR 11398 Error: Invalid network configuration due to missing configuration data
    at _getNetworkConfig (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:1921:9)
    at Function.loadFromConfig (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:114:28)
    at getClientForOrg (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:39:24)
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:103:28)
    at Object.createChannel (/home/hust/user/sp-dashboard/src/app/lib/fabric/index.js:33:26)
    at ChannelService.create_channel (/home/hust/user/sp-dashboard/src/app/service/channel.js:10:15)
    at ChannelController.create_channel (/home/hust/user/sp-dashboard/src/app/controller/channel.js:16:31)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at next (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:45:18)
    at /home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at /home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:36:12
2019-06-27 16:22:13,405 ERROR 11398 [-/127.0.0.1/-/28ms POST /api/create_channel] nodejs.Error: Failed to initialize the channel: Error: Invalid network configuration due to missing configuration data
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:133:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 11398
hostname: hust-H110M-S2

2019-07-02 16:06:54,402 ERROR 17381 [-/127.0.0.1/-/188ms POST /api/create_channel] nodejs.ReferenceError: peerNames is not defined
    at ChannelService.generateNetworkFabricV1_2 (/home/hust/user/sp-dashboard/src/app/service/channel.js:54:14)
    at ChannelService.create_channel (/home/hust/user/sp-dashboard/src/app/service/channel.js:116:32)
    at ChannelController.create_channel (/home/hust/user/sp-dashboard/src/app/controller/channel.js:16:31)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/home/hust/user/sp-dashboard/src/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at next (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:45:18)
    at /home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:44:32)
    at /home/hust/user/sp-dashboard/src/node_modules/koa-compose/index.js:36:12
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/home/hust/user/sp-dashboard/src/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at passportSession (/home/hust/user/sp-dashboard/src/node_modules/egg-passport/lib/framework.js:59:12)
    at <anonymous>

pid: 17381
hostname: hust-H110M-S2

2019-07-02 16:10:17,733 ERROR 17566 Error: ENOENT: no such file or directory, open '/home/hust/user/sp-dashboard/lib/fabric/fixtures/channel/v1.2/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at readFileSync (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/impl/NetworkConfig_1_0.js:446:17)
    at getPEMfromConfig (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/impl/NetworkConfig_1_0.js:435:13)
    at getTLSCACert (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/impl/NetworkConfig_1_0.js:422:10)
    at NetworkConfig_1_0.getCertificateAuthority (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/impl/NetworkConfig_1_0.js:330:6)
    at NetworkConfig_1_0.getOrganization (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/impl/NetworkConfig_1_0.js:286:23)
    at Client._setAdminFromConfig (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:1259:53)
    at Client.loadFromConfig (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:137:9)
    at getClientForOrg (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:40:12)
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:103:28)
    at Object.createChannel (/home/hust/user/sp-dashboard/src/app/lib/fabric/index.js:33:26)
    at ChannelService.create_channel (/home/hust/user/sp-dashboard/src/app/service/channel.js:121:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2019-07-02 16:10:17,733 ERROR 17566 [-/127.0.0.1/-/55ms POST /api/create_channel] nodejs.Error: Failed to initialize the channel: Error: ENOENT: no such file or directory, open '/home/hust/user/sp-dashboard/lib/fabric/fixtures/channel/v1.2/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem'
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:133:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 17566
hostname: hust-H110M-S2

2019-07-02 16:14:31,638 ERROR 17704 Error: ENOENT: no such file or directory, open '/home/hust/user/sp-dashboard/lib/fabric/fixtures/channel/v1.2/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/admin_sk'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at readFileSync (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/impl/NetworkConfig_1_0.js:446:17)
    at getPEMfromConfig (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/impl/NetworkConfig_1_0.js:435:13)
    at NetworkConfig_1_0.getOrganization (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/impl/NetworkConfig_1_0.js:291:18)
    at Client._setAdminFromConfig (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:1259:53)
    at Client.loadFromConfig (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:137:9)
    at getClientForOrg (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:40:12)
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:103:28)
    at Object.createChannel (/home/hust/user/sp-dashboard/src/app/lib/fabric/index.js:33:26)
    at ChannelService.create_channel (/home/hust/user/sp-dashboard/src/app/service/channel.js:121:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2019-07-02 16:14:31,639 ERROR 17704 [-/127.0.0.1/-/34ms POST /api/create_channel] nodejs.Error: Failed to initialize the channel: Error: ENOENT: no such file or directory, open '/home/hust/user/sp-dashboard/lib/fabric/fixtures/channel/v1.2/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/admin_sk'
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:133:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 17704
hostname: hust-H110M-S2

2019-07-02 16:17:23,343 ERROR 17843 Error: Must provide the path to the directory to hold files for the store.
    at new FileKeyValueStore (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-ca-client/lib/impl/FileKeyValueStore.js:36:10)
    at Object.module.exports.newKeyValueStore (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/utils.js:90:25)
    at Function.newDefaultKeyValueStore (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/BaseClient.js:73:19)
    at Client.initCredentialStores (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:1143:23)
    at getClientForOrg (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:42:18)
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:103:28)
    at Object.createChannel (/home/hust/user/sp-dashboard/src/app/lib/fabric/index.js:33:26)
    at ChannelService.create_channel (/home/hust/user/sp-dashboard/src/app/service/channel.js:121:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2019-07-02 16:17:23,344 ERROR 17843 [-/127.0.0.1/-/515ms POST /api/create_channel] nodejs.Error: Failed to initialize the channel: Error: Must provide the path to the directory to hold files for the store.
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:133:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 17843
hostname: hust-H110M-S2

2019-07-02 16:36:04,060 ERROR 18172 Error: EACCES: permission denied, mkdir '/opt/data/client-kvs'
2019-07-02 16:36:04,062 ERROR 18172 [-/127.0.0.1/-/213ms POST /api/create_channel] nodejs.Error: Failed to initialize the channel: Error: EACCES: permission denied, mkdir '/opt/data/client-kvs'
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:133:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 18172
hostname: hust-H110M-S2

2019-07-02 16:37:05,425 ERROR 18266 Error: ENOENT: no such file or directory, open '../../../config/channel.tx/mychannel.tx'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:105:27)
    at <anonymous>
2019-07-02 16:37:05,427 ERROR 18266 [-/127.0.0.1/-/186ms POST /api/create_channel] nodejs.Error: Failed to initialize the channel: Error: ENOENT: no such file or directory, open '../../../config/channel.tx/mychannel.tx'
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:133:13)
    at <anonymous>

pid: 18266
hostname: hust-H110M-S2

2019-07-02 16:38:46,350 ERROR 18403 Error: ENOTDIR: not a directory, open '../config/channel.tx/mychannel.tx'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:105:27)
    at <anonymous>
2019-07-02 16:38:46,351 ERROR 18403 [-/127.0.0.1/-/185ms POST /api/create_channel] nodejs.Error: Failed to initialize the channel: Error: ENOTDIR: not a directory, open '../config/channel.tx/mychannel.tx'
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:133:13)
    at <anonymous>

pid: 18403
hostname: hust-H110M-S2

2019-07-02 16:40:48,618 ERROR 18551 Error: "orderer" request parameter is missing and there are no orderers defined on this channel in the network configuration
    at Client.getTargetOrderer (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:1771:12)
    at Client._createOrUpdateChannel (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:755:24)
    at Client.createChannel (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:718:15)
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:117:37)
    at <anonymous>
2019-07-02 16:40:48,620 ERROR 18551 [-/127.0.0.1/-/268ms POST /api/create_channel] nodejs.Error: Failed to initialize the channel: Error: "orderer" request parameter is missing and there are no orderers defined on this channel in the network configuration
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:133:13)
    at <anonymous>

pid: 18551
hostname: hust-H110M-S2

2019-07-02 17:06:22,927 ERROR 19168 Error: "orderer" request parameter is missing and there are no orderers defined on this channel in the network configuration
    at Client.getTargetOrderer (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:1771:12)
    at Client._createOrUpdateChannel (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:755:24)
    at Client.createChannel (/home/hust/cello/cello/src/user-dashboard/src/packages/fabric-1.2/node_modules/fabric-client/lib/Client.js:718:15)
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:118:37)
    at <anonymous>
2019-07-02 17:06:22,928 ERROR 19168 [-/127.0.0.1/-/202ms POST /api/create_channel] nodejs.Error: Failed to initialize the channel: Error: "orderer" request parameter is missing and there are no orderers defined on this channel in the network configuration
    at Application.createChannel [as createChannelV1_2] (/home/hust/user/sp-dashboard/src/app/lib/fabric/v1_2.js:134:13)
    at <anonymous>

pid: 19168
hostname: hust-H110M-S2

